language: d
d:
- dmd
- ldc
sudo: false
before_install:
- pip install --user codecov
- dub fetch packageversion
script:
- dub test --compiler=${DC} --coverage
- dub build --compiler=${DC} --build=ddox
after_success:
- codecov
addons:
  apt:
    packages:
    - libevent-dev
deploy:
  github-token: "$GH_REPO_TOKEN"
  local-dir: docs
  keep-history: true
  skip-cleanup: true
  on:
    branch: master
  verbose: true
  provider: pages
env:
  global:
    secure: Ybt0NjFU1nqRUtMnY1I23z2AbxjI2+zLvdp04jSq7nObu/SfT7ZEGTlCsUuQc1/2gmqzUgVXZfKMocIkYqDgAFyxfK7i0K4WXPqhCGYCCkJ+rMnENJWnOmQRsmAYTWLHaUmfXR5tuseZ5/jwN7qU1M7teGalMidZHUiSETsudN3VMqVUDQdn1xzLuiC9YtSxv34Ibpgqi9Y7qs/EeN0JKqla8hqz+ggLkpsRGBxl0N3m5lTRuyFBNbz365clcS0TDeDsVM3nVLg/Z8+poRcNY3oKaZw8RvzMR3V1AVBA7SuUe9CVE9qRrn7JVozAhSCG4tzSo/DikrSXGtYqgGsQxQehbVYloz7HXn4P+ioXLwsO7O+U1zkAxpDxtjI2TbEOKytE3bD/goWjaTVyP54N0GGlbHlZO+jDG+BrdzY2BD7dMmWQxOsrLEp7KRI5WGaNdMCJCQJ9LATm5kxxYdoklXpgBN55zLQapeblVSrauhQyJ0Kh2M9ZppeOSSpJzoEIWMydTNfGsX3hBC8nsJuKiwVgPHBdJtfEkam5/LHQJTVwlE0kyNV2bTl1JohYOAGLPse/MNnG2egJurSrH93G43OAuC9Ei/A3TZohqAzegiB+mDZ75ofg6D3sSykNb8fOVfBlIQrU1ie8ExbRztna5afULzeP1GBAsuu8FRaMV+g=
